### ISSUE TITLE
Recipe App Group Project: Set up Kenban Board

### ISSUE THREAD

**Issue by ericmahare** [ericmahare/Recipe-App#8]
### Rails Group project: set up kanban board

In this group  we are 2 and we assigned the tasks as described below:

- `Team member #1` is @ericmahare 
- `Team member #2` is @carlylechia 

Here is the link to our kanban board: [project kanban board](https://github.com/users/ericmahare/projects/3/views/1?layout=board)

**Comment by youmari** [comment]
Hi, @ericmahare @carlylechia , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

### Highlights
✔️ using points for each card
✔️ Card for each requirement

## Required Changes ♻️

- [ ] it would be better to add a description to this [Card](https://github.com/ericmahare/Recipe-App/issues/6) so it can be understandable and detailed of what you should do

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by youmari** [comment]
# Project Approved :trophy: :tada: 🟢 

Hi @ericmahare @carlylechia 

Your project is complete!  You have done it exceptionally well. it's time to merge it :100: 
Congratulations! 🎉 

### To Highlight :+1: 

:heavy_check_mark: No linters error.
:heavy_check_mark: Details PR title and description.
:heavy_check_mark: Good commit messages.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also connect with me on [slack](https://microverse-students.slack.com/team/U02FTTCCU2V)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).
